name: Mutation

on:
  create:
    tags:
     - v*
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '44 16 * * *' # Run mutation tests every day at 16:44 UTC.
    # Time chosen randomly.

permissions: {}

jobs:
  psalm:
    name: Infection on PHP ${{ matrix.php-versions }}
    runs-on: ${{ matrix.operating-system }}
    permissions:
      contents: read
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['8.4']
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@db91e1a0e48e84637d325a7ee4d2677e146ceec4  # v2.36.0
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: pcov

      - name: Add Infection as dependency
        run: composer require --dev infection/infection

      - name: Update dependencies
        run: composer update

      - name: Mutation Tests
        run: vendor/bin/infection

      - name: Print the mutation.log file for easy copy/paste from GitHub Actions
        run: cat infection.log
