name: PHPStan

on: [push, pull_request]

permissions: {}

jobs:
  phpstan:
    name: PHPStan on PHP ${{ matrix.php-versions }}
    runs-on: ${{ matrix.operating-system }}
    permissions:
      contents: read
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['8.4']
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@db91e1a0e48e84637d325a7ee4d2677e146ceec4  # v2.36.0
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpstan:1
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@b38926e6aa883a48335a05214b1d7afe9d9913ca  # v3.1.1

      - name: Initialize Database
        run: php cmd/init.php

      - name: Static Analysis
        run: vendor/bin/phpstan analyse --memory-limit 1024M
